# Generated by Django 6.0.8 on 2026-09-04 08:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='codename')),
                ('resource', models.CharField(db_index=True, max_length=50, verbose_name='resource')),
                ('action', models.CharField(max_length=50, verbose_name='action')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='organization name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('logo_url', models.CharField(blank=True, default='', max_length=1024, verbose_name='logo URL')),
                ('website', models.CharField(blank=True, default='', max_length=500, verbose_name='website')),
                ('company_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='company email')),
                ('company_address', models.TextField(blank=True, default='', verbose_name='company address')),
                ('company_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='company phone')),
                ('default_currency', models.CharField(default='USD', max_length=3, verbose_name='default currency')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='default tax rate')),
                ('default_notes', models.TextField(blank=True, default='', verbose_name='default invoice notes')),
                ('default_terms', models.TextField(blank=True, default='', verbose_name='default invoice terms')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Stripe customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe subscription ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='role name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_system', models.BooleanField(default=False, help_text='Designates whether this is a seeded default system role', verbose_name='is system role')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='orgs.organization', verbose_name='organization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='orgs.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email address')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='member name')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='department')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='invited at')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='joined at')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_memberships', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.organization', verbose_name='organization')),
                ('roles', models.ManyToManyField(blank=True, related_name='memberships', to='orgs.role', verbose_name='roles')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='invited email')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='department')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='invitation token')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='orgs.organization', verbose_name='organization')),
                ('roles', models.ManyToManyField(blank=True, related_name='invites', to='orgs.role', verbose_name='roles')),
            ],
            options={
                'verbose_name': 'invite',
                'verbose_name_plural': 'invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_role_name'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_org_member_email'),
        ),
    ]
