# Generated by Django 6.0.8 on 2026-09-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Stripe customer ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe subscription ID'),
        ),
    ]
