# Generated by Django 6.0.8 on 2026-09-04 09:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0002_alter_organization_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=100, verbose_name='feature')),
                ('model', models.CharField(max_length=255, verbose_name='model')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='prompt tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='completion tokens')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='latency (ms)')),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=8, verbose_name='cost estimate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='orgs.organization', verbose_name='organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI Log',
                'verbose_name_plural': 'AI Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
