# Generated by Django 6.0.8 on 2026-09-04 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Full Name')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='Avatar URL')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Company Name')),
                ('company_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Company Email')),
                ('company_address', models.TextField(blank=True, default='', verbose_name='Company Address')),
                ('company_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Company Phone')),
                ('default_currency', models.CharField(default='USD', max_length=10, verbose_name='Default Currency')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Default Tax Rate')),
                ('default_notes', models.TextField(blank=True, default='', verbose_name='Default Notes')),
                ('default_terms', models.TextField(blank=True, default='', verbose_name='Default Terms')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
