# Generated by Django 6.0.8 on 2026-09-04 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='organization id')),
                ('actor_email', models.EmailField(blank=True, max_length=254, verbose_name='actor email')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='action')),
                ('target_model', models.CharField(db_index=True, max_length=128, verbose_name='target model')),
                ('target_id', models.CharField(db_index=True, max_length=128, verbose_name='target id')),
                ('changes_diff', models.JSONField(blank=True, default=dict, verbose_name='changes diff')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', '-created_at'], name='core_auditl_organiz_e98001_idx'), models.Index(fields=['target_model', 'target_id'], name='core_auditl_target__315580_idx')],
            },
        ),
    ]
