# Generated by Django 6.0.8 on 2026-09-04 09:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0002_alter_organization_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Product ID')),
                ('tier', models.PositiveSmallIntegerField(default=0, verbose_name='tier')),
                ('trial_days', models.PositiveIntegerField(default=14, verbose_name='trial days')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Stripe Event ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Stripe event',
                'verbose_name_plural': 'Stripe events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_price_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Price ID')),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=20, verbose_name='interval')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'price mapping',
                'verbose_name_plural': 'price mappings',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Subscription ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('paused', 'Paused')], default='trialing', max_length=30, verbose_name='status')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='trial start')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='trial end')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='current period start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='current period end')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='cancel at period end')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='orgs.organization', verbose_name='organization')),
                ('pending_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='billing.plan', verbose_name='pending plan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('value', models.JSONField(default=dict, verbose_name='value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='billing.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'plan entitlement',
                'verbose_name_plural': 'plan entitlements',
                'constraints': [models.UniqueConstraint(fields=('plan', 'key'), name='unique_plan_entitlement')],
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='orgs.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'usage counter',
                'verbose_name_plural': 'usage counters',
                'constraints': [models.UniqueConstraint(fields=('organization', 'key', 'period_start'), name='unique_org_usage_counter_period')],
            },
        ),
    ]
