# Generated by Django 6.0.8 on 2026-09-04 08:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0002_alter_organization_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='phone number')),
                ('address', models.TextField(blank=True, default='', verbose_name='billing address')),
                ('company', models.CharField(blank=True, default='', max_length=255, verbose_name='company name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='orgs.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='expense title')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('salaries', 'Salaries'), ('marketing', 'Marketing'), ('supplies', 'Supplies'), ('software', 'Software'), ('travel', 'Travel'), ('taxes', 'Taxes'), ('other', 'Other')], db_index=True, default='other', max_length=50, verbose_name='expense category')),
                ('vendor', models.CharField(blank=True, default='', max_length=255, verbose_name='vendor / merchant')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='expense date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='card', max_length=50, verbose_name='payment method')),
                ('receipt_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='receipt URL')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='orgs.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, verbose_name='invoice number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='issue date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='tax rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount amount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('terms', models.TextField(blank=True, default='', verbose_name='terms')),
                ('business_name', models.CharField(blank=True, default='', max_length=255, verbose_name='business name snapshot')),
                ('business_email', models.CharField(blank=True, default='', max_length=255, verbose_name='business email snapshot')),
                ('business_address', models.TextField(blank=True, default='', verbose_name='business address snapshot')),
                ('business_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='business phone snapshot')),
                ('client_name', models.CharField(blank=True, default='', max_length=255, verbose_name='client name snapshot')),
                ('client_email', models.CharField(blank=True, default='', max_length=255, verbose_name='client email snapshot')),
                ('client_address', models.TextField(blank=True, default='', verbose_name='client address snapshot')),
                ('stock_deducted', models.BooleanField(default=False, verbose_name='stock deducted')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='erp.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orgs.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='last number')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='orgs.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'invoice sequence',
                'verbose_name_plural': 'invoice sequences',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='payment amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='bank_transfer', max_length=50, verbose_name='payment method')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='payment date')),
                ('reference', models.CharField(blank=True, default='', max_length=255, verbose_name='reference number')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.invoice', verbose_name='invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orgs.organization', verbose_name='organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='unit price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='category')),
                ('unit', models.CharField(blank=True, default='item', max_length=50, verbose_name='unit')),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='SKU')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='stock quantity')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='low stock threshold')),
                ('track_stock', models.BooleanField(default=False, verbose_name='track stock')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orgs.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='quantity')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='unit rate')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='line total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.invoice', verbose_name='invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='erp.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization', 'status'], name='idx_client_org_status'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'category'], name='idx_expense_org_category'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'expense_date'], name='idx_expense_org_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='idx_invoice_org_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'issue_date'], name='idx_invoice_org_issue_date'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='unique_org_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.UniqueConstraint(fields=('organization', 'year'), name='unique_org_year_invoice_sequence'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'payment_date'], name='idx_payment_org_date'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_active'], name='idx_product_org_active'),
        ),
    ]
